name: Build and publish app Docker image CI

on:
  push:
    branches:
      - main
    tags:
      - "*"  # Trigger when a tag is pushed
    paths:
      - "app/**"  # Trigger only if changes occur in the /app directory

jobs:
  app-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker Image tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            TAG_NAME="${GITHUB_SHA}"
          fi
          echo "TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            aliyousefian/myt-devops-assignment-app:latest
            aliyousefian/myt-devops-assignment-app:${{ env.TAG }}
